# Generated by Django 5.0 on 2023-12-19 15:09

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=500)),
                ("birthdate", models.DateField()),
                ("street", models.CharField(max_length=500)),
                ("building", models.PositiveIntegerField()),
                (
                    "postal_code",
                    models.CharField(
                        max_length=8,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Insira um Código-Postal válido.",
                                regex="^\\d{4}-\\d{3}$",
                            )
                        ],
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="District",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name="Librarian",
            fields=[
                (
                    "contact_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="users.contact",
                    ),
                ),
                (
                    "librarian_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("salary", models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            bases=("users.contact",),
        ),
        migrations.CreateModel(
            name="Reader",
            fields=[
                (
                    "contact_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="users.contact",
                    ),
                ),
                (
                    "reader_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("requisition_count", models.PositiveIntegerField(default=0)),
                (
                    "fines_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
            ],
            bases=("users.contact",),
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=300)),
                (
                    "district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.district"
                    ),
                ),
            ],
        ),
    ]
