# Generated by Django 4.2.8 on 2023-12-20 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_contact_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="district",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.district",
            ),
        ),
    ]
