# Generated by Django 4.2.8 on 2023-12-20 23:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_contact_district"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="username",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
