# Generated by Django 4.2.8 on 2023-12-20 23:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_alter_contact_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                default="images/default-profile.png",
                null=True,
                upload_to="profiles/",
            ),
        ),
    ]
