# Generated by Django 4.2.8 on 2023-12-21 00:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_contact_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="birthdate",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="contact",
            name="building",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="contact",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                max_length=1,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="postal_code",
            field=models.CharField(
                blank=True,
                max_length=8,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Insira um Código-Postal válido.",
                        regex="^\\d{4}-\\d{3}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="street",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="reader",
            name="fines_value",
            field=models.DecimalField(
                decimal_places=2, default=0, editable=False, max_digits=5
            ),
        ),
        migrations.AlterField(
            model_name="reader",
            name="requisition_count",
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
