# Generated by Django 5.0 on 2023-12-24 18:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0011_alter_librarian_salary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="profile_image",
            field=models.ImageField(
                blank=True, default="user-default.png", null=True, upload_to="profiles/"
            ),
        ),
    ]
