# Generated by Django 5.0 on 2023-12-26 22:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0012_alter_contact_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Masculino"), ("F", "Feminino"), ("O", "Outro")],
                max_length=1,
                null=True,
            ),
        ),
    ]
