# Generated by Django 5.0 on 2023-12-10 18:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=5)),
                ("flag", models.ImageField(upload_to="images/country_flags/")),
            ],
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                ("caption", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Publisher",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=100)),
                ("logo", models.ImageField(upload_to="images/publisher_logos")),
                ("email", models.EmailField(max_length=254)),
                ("website", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="Content",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                ("title", models.CharField(max_length=250)),
                ("publication_date", models.DateField()),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("genre", models.ManyToManyField(to="core.genre")),
                (
                    "publisher",
                    models.ForeignKey(
                        default="Editora não especificada",
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to="core.publisher",
                    ),
                ),
            ],
        ),
    ]
