# Generated by Django 5.0 on 2023-12-10 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_content_options_alter_country_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="content",
            name="publisher",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.publisher",
            ),
        ),
    ]
