# Generated by Django 4.2.8 on 2023-12-23 01:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_alter_country_flag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="country",
            name="flag",
            field=models.ImageField(blank=True, upload_to="images/country-flags/"),
        ),
    ]
