# Generated by Django 4.2.8 on 2023-12-23 01:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_alter_publisher_logo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publisher",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
