# Generated by Django 5.0 on 2023-12-25 22:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_alter_content_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="genre",
            name="caption",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
