# Generated by Django 5.0 on 2023-12-15 22:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0003_rename_author_book_authors"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="slug",
        ),
    ]
