# Generated by Django 5.0 on 2023-12-19 14:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0004_remove_book_slug"),
    ]

    operations = [
        migrations.RenameField(
            model_name="author",
            old_name="creation_date",
            new_name="created",
        ),
    ]
