# Generated by Django 5.0 on 2023-12-19 16:04

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0006_rename_creation_date_content_created_and_more"),
        ("users", "0002_contact_district"),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "rating",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                (
                    "review_text",
                    models.TextField(blank=True, max_length=1000, null=True),
                ),
                (
                    "content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.content"
                    ),
                ),
                (
                    "reder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.reader"
                    ),
                ),
            ],
        ),
    ]
