# Generated by Django 5.0 on 2023-12-19 15:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("requisitions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="requisition",
            name="fine",
            field=models.DecimalField(
                decimal_places=2, default=0, editable=False, max_digits=5
            ),
        ),
    ]
