# Generated by Django 5.0 on 2023-12-15 22:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0004_content_language_content_summary_alter_country_flag"),
    ]

    operations = [
        migrations.CreateModel(
            name="Director",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("birthdate", models.DateField()),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                ("biography", models.TextField(blank=True)),
                ("picture", models.ImageField(upload_to="images/directors/")),
                (
                    "country",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.country",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "content_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.content",
                    ),
                ),
                ("duration_minutes", models.PositiveIntegerField()),
                ("media_type", models.CharField(max_length=10)),
                ("cover", models.ImageField(upload_to="images/movies/")),
                ("trailer", models.URLField()),
                (
                    "directors",
                    models.ManyToManyField(related_name="movies", to="movies.director"),
                ),
            ],
            bases=("core.content",),
        ),
    ]
